### ISSUE TITLE
Map crashing on jelly bean devices

### ISSUE THREAD

**Issue by dheerajsinghanktech** [googlemaps/android-samples#11]
Getting below errors on jelly bean devices

02-18 17:39:23.951 15029-15029/? E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.nb.a
02-18 17:39:24.098 15029-15029/? E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.mw.a

Same app crashing on android simulator 
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.activity.ShowLocationActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class fragment
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sanjay555** [comment]
Did you downgraded play-service?.
