### ISSUE TITLE
Fatal Exception: com.google.android.libraries.maps.jy.zzb: tname=DefaultPool7

### ISSUE THREAD

**Issue by ragummrsa2930** [googlemaps/android-samples#314]
Fatal Exception: com.google.android.libraries.maps.jy.zzb: tname=DefaultPool7 - Not on the main thread
       at com.google.android.libraries.maps.jx.zzo.zzb(Preconditions.java:11)
       at com.google.android.libraries.maps.jx.zzu.zza(ThreadChecker.java:5)
       at com.google.android.libraries.maps.jw.zzd.run(Authorizer.java:58)
       at com.google.android.libraries.maps.jw.zzd.zza(Authorizer.java:36)
       at com.google.android.libraries.maps.jw.zzd.zza(Authorizer.java:77)
       at com.google.android.libraries.maps.ke.zzb.zza(ApiTokenProviderPhoenix.java:4)
       at com.google.android.libraries.maps.fi.zza.zzb(ApiTokenRequirement.java:12)
       at com.google.android.libraries.maps.fi.zza.zza(ApiTokenRequirement.java:15)
       at com.google.android.libraries.maps.fg.zzf.zza(:50)
       at com.google.android.libraries.maps.iy.zzn.zza(RetryingFuture.java:9)
       at com.google.android.libraries.maps.jj.zze.zza(AbstractTransformFuture.java:7)
       at com.google.android.libraries.maps.jj.zzf.run(AbstractTransformFuture.java:36)
       at com.google.android.libraries.maps.jj.zzak.run(MoreExecutors.java:3)
       at com.google.android.libraries.maps.fv.zzc.run(CancelableRunnable.java:7)
       at com.google.android.libraries.maps.fv.zzae.run(Task.java:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.libraries.maps.fv.zzv.run(GmmThread.java:10)
       at java.lang.Thread.run(Thread.java:764)

"MY code" all are in main activity thread itself but still i dont know why the above crash is happening in production app. Strange thing is im not able to reproduce this issue. 

SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.mapFragment);
        mapFragment.getMapAsync(this);

@Override
    public void onMapReady(GoogleMap googleMap) {
        this.googleMap = googleMap;
        setupMap();
    }

**Comment by ragummrsa2930** [comment]
Any update on this? is this bug in google map latest version 3.0.1 beta? So is there any issue in my app side? we are receiving more than 10 crash each day. Should i downgrade the google map sdk?

**Comment by kirvis250** [comment]
From Firebase:

Devices: Samsung Galaxy S7 ; Lenovo Tab M10 (FHD)
OS: Android 8, Android 9
Device states: 100% background


Correct me if I'm wrong, but this happens when App is in background?

**Comment by arriolac** [comment]
Since this issue is related to the Maps BETA library itself, the best place to receive support for this and surface this to our engineering team is by filing an issue in our issue tracker [here](https://issuetracker.google.com/issues/new?component=188870&template=788712).

**Comment by danilshik** [comment]
I confirm the error when migrating to the new sdk beta

**Comment by samstenner2** [comment]
Also encountering this bug on occasion

**Comment by Del-S** [comment]
We are also encountering this issue on about 2,6k devices. It also seems there is already an issue in google issue tracker: https://issuetracker.google.com/issues/186436360.

**Comment by dilankafernando** [comment]
I had the same issue. What I did, checked the internet connection before using the method that related to google com.google.android.libraries.maps.....
In this case before "mapFragment.getMapAsync(this);"

**Xamarine Android**

if(reachability.Has_Internet()){
    mapFragment.getMapAsync(this);
}

 public bool Has_Internet()
        {
            var access = Connectivity.NetworkAccess;
            switch (access) {
                case NetworkAccess.None: 
                case NetworkAccess.Unknown: 
                case NetworkAccess.ConstrainedInternet:
                case NetworkAccess.Local:
                    return false;
                case NetworkAccess.Internet:
                    return true;
                default:
                    return false;
            }

        }



This is the idea, do a similar thing before access google library.

**Comment by kikoso** [comment]
Closing this issue, since it was related to an old Maps SDK version.
