### ISSUE TITLE
Permission request infinite loop

### ISSUE THREAD

**Issue by iceteahh** [googlemaps/android-samples#53]
Project: CurrentPlaceDetailsOnMap
Emulator: Galaxy Nexus APi level 25
Android 7.1.1

Loop between:

```
private void updateLocationUI() {
        if (mMap == null) {
            return;
        }

        /*
         * Request location permission, so that we can get the location of the
         * device. The result of the permission request is handled by a callback,
         * onRequestPermissionsResult.
         */
        if (ContextCompat.checkSelfPermission(this.getApplicationContext(),
                android.Manifest.permission.ACCESS_FINE_LOCATION)
                == PackageManager.PERMISSION_GRANTED) {
            mLocationPermissionGranted = true;
        } else {
            ActivityCompat.requestPermissions(this,
                    new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION},
                    PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION);
        }

        if (mLocationPermissionGranted) {
            mMap.setMyLocationEnabled(true);
            mMap.getUiSettings().setMyLocationButtonEnabled(true);
        } else {
            mMap.setMyLocationEnabled(false);
            mMap.getUiSettings().setMyLocationButtonEnabled(false);
            mLastKnownLocation = null;
        }
    }
```
And

```
@Override
    public void onRequestPermissionsResult(int requestCode,
                                           @NonNull String permissions[],
                                           @NonNull int[] grantResults) {
        mLocationPermissionGranted = false;
        switch (requestCode) {
            case PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION: {
                // If request is cancelled, the result arrays are empty.
                if (grantResults.length > 0
                        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    mLocationPermissionGranted = true;
                }
            }
        }
        updateLocationUI();
    }
```

Log:

```
03-22 23:34:18.249 24660-24660/com.example.mypc.mapdemo W/Activity: Can reqeust only one set of permissions at a time
03-22 23:34:19.759 24660-24660/com.example.mypc.mapdemo W/Activity: Can reqeust only one set of permissions at a time
03-22 23:34:20.501 24660-24660/com.example.mypc.mapdemo W/Activity: Can reqeust only one set of permissions at a time
03-22 23:34:20.894 24660-24660/com.example.mypc.mapdemo W/Activity: Can reqeust only one set of permissions at a time
```

Crash

```
E/AndroidRuntime:     at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:372)
                                                       at com.example.mypc.mapdemo.MainActivity.updateLocationUI(MainActivity.java:330)
                                                       at com.example.mypc.mapdemo.MainActivity.onRequestPermissionsResult(MainActivity.java:207)
                                                       at android.app.Activity.requestPermissions(Activity.java:4116)
                                                       at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompatApi23.java:49)
                                                       at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:37
```2)

**Comment by swifthorseman** [comment]
Facing the same issue in the **CurrentPlaceDetailsOnMap** project.
Using the emulator: Nexus 5X API 25 x86 (Android 7.1.1, API 25)

**Comment by v-gar** [comment]
I could reproduce this error, too.
My solution was placing the `updateLocationUI();` into the if-branch so it'll only be executed (and the location UI updated) again if the user accepts the permission request. Otherwise it tries to refresh the location (and the permission request) without any (positive) permission result again and again which causes the loop.
```
@Override
public void onRequestPermissionsResult(int requestCode,
                                       @NonNull String permissions[],
                                       @NonNull int[] grantResults) {
    mLocationPermissionGranted = false;
    switch (requestCode) {
        case PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION: {
            // If request is cancelled, the result arrays are empty.
            if (grantResults.length > 0
                    && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                mLocationPermissionGranted = true;
                updateLocationUI();
            }
        }
    }
}
```

**Comment by da2ana** [comment]
I'm facing the same issue and placing  updateLocationUI();  into the if-branch didn't fix it
