### ISSUE TITLE
The provided context is not an application context | Google Map not working Arabic 

### ISSUE THREAD

**Issue by skbhati199** [googlemaps/android-samples#599]
Hello All, Please help me,
 
I'm using Kotlin 

 startKoin {
            androidLogger(Level.DEBUG)
            androidContext(this@MyApplication)
            modules(listOf(databaseVMModule, sharedVMlModule, fragmentsModule, repositoryModule))
        }
        
         <FrameLayout
                    android:layoutDirection="ltr"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent">
                    <fragment
                        android:tag="map"
                        android:id="@+id/mapFragment"
                        android:name="com.google.android.gms.maps.SupportMapFragment"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        app:cameraZoom="16" />

                </FrameLayout>

We change Arabic language locale it gives error, Please help what exact issue koin or kotlin or Map xml    Caused by: java.lang.IllegalStateException: The provided context is not an application context
        at 
 
 
 Caused by: android.view.InflateException: Binary XML file line #42 in com.emojizone:layout/activity_home: Binary XML file line #42 in com.emojizone:layout/activity_home: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #42 in com.emojizone:layout/activity_home: Error inflating class fragment
     Caused by: java.lang.IllegalStateException: The provided context is not an application context
        at com.google.maps.api.android.lib6.common.m.c(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):2)
        
        E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.emojizone, PID: 32113
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.emojizone/com.emojizone.ui.home.HomeActivity}: android.view.InflateException: Binary XML file line #42 in com.emojizone:layout/activity_home: Binary XML file line #42 in com.emojizone:layout/activity_home: Error inflating class fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #42 in com.emojizone:layout/activity_home: Binary XML file line #42 in com.emojizone:layout/activity_home: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #42 in com.emojizone:layout/activity_home: Error inflating class fragment
     Caused by: java.lang.IllegalStateException: The provided context is not an application context
        at com.google.maps.api.android.lib6.common.m.c(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):2)
        at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):4)
        at com.google.android.gms.maps.internal.CreatorImpl.newMapFragmentDelegate(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):2)
        at com.google.android.gms.maps.internal.g.a(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):22)
        at cy.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201817052@20.18.17 (040700-0):4)
        at android.os.Binder.transact(Binder.java:1043)
        at com.google.android.gms.internal.maps.zza.zzH(com.google.android.gms:play-services-maps@@17.0.1:2)
        at com.google.android.gms.maps.internal.zze.zzd(com.google.android.gms:play-services-maps@@17.0.1:3)
        at com.google.android.gms.maps.zzav.zza(com.google.android.gms:play-services-maps@@17.0.1:4)
        at com.google.android.gms.maps.zzav.createDelegate(com.google.android.gms:play-services-maps@@17.0.1:1)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(com.google.android.gms:play-services-base@@17.5.0:18)
        at com.google.android.gms.dynamic.DeferredLifecycleHelper.onInflate(com.google.android.gms:play-services-base@@17.5.0:20)
        at com.google.android.gms.maps.SupportMapFragment.onInflate(com.google.android.gms:play-services-maps@@17.0.1:9)
        at androidx.fragment.app.Fragment.onInflate(Fragment.java:1488)
        at androidx.fragment.app.FragmentManagerImpl.onCreateView(FragmentManagerImpl.java:3204)
        at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:134)
        at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:357)
        at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:336)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1067)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
E/AndroidRuntime:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:303)
        at androidx.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at com.emojizone.base.SimpleBaseActivity.onCreate(SimpleBaseActivity.kt:62)
        at com.emojizone.base.BaseActivity.onCreate(BaseActivity.kt:20)
        at com.emojizone.ui.home.HomeActivity.onCreate(HomeActivity.kt:134)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
W/System: A resource failed to call release. 
V/FA: Connection attempt already in progress
[activity_home.txt](https://github.com/googlemaps/android-samples/files/6732948/activity_home.txt)

**Comment by arriolac** [comment]
Can you give more context how this error occurs (e.g. on activity launch? on fragment launch?) etc.

**Comment by mwaked** [comment]
I have the same issue.
Any update??

**Comment by Serpivskyi** [comment]
The same, need some updates...

**Comment by arriolac** [comment]
This appears to be an issue with the Maps SDK itself, and not this sample repo. Please file a ticket in the [issue tracker](https://issuetracker.google.com/issues/new?component=188870&template=788712) along with detailed repro steps.

**Comment by Serpivskyi** [comment]
@arriolac maybe you can give us some relevant update or some comment  how to fix this? This is abnormal behavior of the sdk
