### ISSUE TITLE
"Get Place" crashing and Markers

### ISSUE THREAD

**Issue by jacksonsfranca** [googlemaps/android-samples#65]
I was using the sample here, about Maps and how to get the Current Location, also following the tutorial available by this link(https://developers.google.com/maps/documentation/android-api/current-place-tutorial#get-the-location-of-the-android-device-and-position-the-map)

When I was testing it, I had and issue when I clicked on "GET PLACE", and then the app Crashed, this is the error list:
08-11 14:40:55.667 20886-20886/com.example.currentplacedetailsonmap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                      Process: com.example.currentplacedetailsonmap, PID: 20886
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                                          at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:401)
                                                                                          at android.widget.ArrayAdapter.getView(ArrayAdapter.java:369)
                                                                                          at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                          at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
                                                                                          at android.widget.ListView.onMeasure(ListView.java:1188)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:135)
                                                                                          at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5954)
                                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                          at android.view.View.measure(View.java:18804)
                                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2112)
                                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1203)
                                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1464)
                                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                          at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                          at android.os.Handler.handleCallback(Handler.java:746)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

And the Marker for my Current Location isn't showing, just a blue marker (not the red one).

How can I solve this? Can you guys help me?

**Comment by wangela** [comment]
Marking as obsolete
