### ISSUE TITLE
Instant Run Problem

### ISSUE THREAD

**Issue by maxcorrads** [googlemaps/android-samples#67]
Hello,
I have problems with Instant Run and Google Maps,
the problems occur with any project, ApiDemos or Tutorials (in this case MapWithMarker).

To reproduce it just build and run the app, when it's open change something and do an instant run, for example in activity_maps.xml:
BEFORE
```
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/map"
    android:name="com.google.android.gms.maps.SupportMapFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.mapwithmarker.MapsMarkerActivity" />
```
AFTER:
```
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/map"
    android:name="com.google.android.gms.maps.SupportMapFragment"
    android:layout_width="match_parent"
    android:layout_height="300dp"
    tools:context="com.example.mapwithmarker.MapsMarkerActivity" />

```

ERROR:
```
08-16 11:51:24.820 11071-11123/com.example.mapwithmarker D/EGL_emulation: eglMakeCurrent: 0x9cb204a0: ver 2 0 (tinfo 0x9cb23b80)
08-16 11:51:24.853 11071-11071/com.example.mapwithmarker I/Google Maps Android API: Google Play services package version: 11302470
08-16 11:51:24.858 11071-11071/com.example.mapwithmarker W/ResourceType: For resource 0x7f07000e, entry index(14) is beyond type entryCount(1)
08-16 11:51:24.858 11071-11071/com.example.mapwithmarker W/ResourceType: Failure getting entry for 0x7f07000e (t=6 e=14) (error -75)
08-16 11:51:24.865 11071-11071/com.example.mapwithmarker D/AndroidRuntime: Shutting down VM
08-16 11:51:24.865 11071-11071/com.example.mapwithmarker E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.example.mapwithmarker, PID: 11071
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.mapwithmarker/com.example.mapwithmarker.MapsMarkerActivity}: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class fragment
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
                                                                               at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                            Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class fragment
                                                                            Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class fragment
                                                                            Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f07000e
                                                                               at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
                                                                               at android.content.res.Resources.getDimensionPixelSize(Resources.java:667)
                                                                               at com.google.maps.api.android.lib6.impl.aq.i(:com.google.android.gms.DynamiteModulesB:69)
                                                                               at com.google.maps.api.android.lib6.impl.fj.<init>(:com.google.android.gms.DynamiteModulesB:19)
                                                                               at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:42)
                                                                               at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:1)
                                                                               at com.google.maps.api.android.lib6.impl.cl.a(:com.google.android.gms.DynamiteModulesB:24)
                                                                               at com.google.android.gms.maps.internal.s.onTransact(:com.google.android.gms.DynamiteModulesB:45)
                                                                               at android.os.Binder.transact(Binder.java:499)
                                                                               at com.google.android.gms.maps.internal.IMapFragmentDelegate$zza$zza.onCreateView(Unknown Source)
                                                                               at com.google.android.gms.maps.SupportMapFragment$zza.onCreateView(Unknown Source)
                                                                               at com.google.android.gms.dynamic.zza$4.zzb(Unknown Source)
                                                                               at com.google.android.gms.dynamic.zza.zza(Unknown Source)
                                                                               at com.google.android.gms.dynamic.zza.onCreateView(Unknown Source)
                                                                               at com.google.android.gms.maps.SupportMapFragment.onCreateView(Unknown Source)
                                                                               at android.support.v4.app.Fragment.performCreateView(Fragment.java:2080)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1065)
                                                                               at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
                                                                               at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2442)
                                                                               at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
                                                                               at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:376)
                                                                               at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
                                                                               at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                               at com.example.mapwithmarker.MapsMarkerActivity.onCreate(MapsMarkerActivity.java:23)
                                                                               at android.app.Activity.performCreate(Activity.java:6679)
08-16 11:51:24.865 11071-11071/com.example.mapwithmarker E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                               at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
                                                                               at android.app.ActivityThread.-wrap19(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by sreekanth-krishnan** [comment]
I'm having this issue for sometime now and haven't found a solution

**Comment by ganjarramadhan** [comment]
I'm also having this issue. is there anyone who knows how to solve this?

**Comment by sreekanth-krishnan** [comment]
I’ve reported the issue here https://issuetracker.google.com/issues/66402372

**Comment by katherineallen** [comment]
Thanks for reporting this issue on the Issue Tracker. Since it's being tracked there, I'm going to close it here for now.
