### ISSUE TITLE
Crash in camera demo activity

### ISSUE THREAD

**Issue by alishari** [googlemaps/android-samples#795]
Kotlin version of ApiDemos crashed when I wanted to open the Camera demo. It seems the initialization of the map object was removed by mistake in [this commit](https://github.com/googlemaps/android-samples/commit/4ee2170919da1646212483fbe643a2b471dba096).

Logs:
```
    Process: com.example.kotlindemos.gms, PID: 2626
    kotlin.UninitializedPropertyAccessException: lateinit property map has not been initialized
        at com.example.kotlindemos.CameraDemoActivity.addCameraTargetToPath(CameraDemoActivity.kt:377)
        at com.example.kotlindemos.CameraDemoActivity.onCameraMoveStarted(CameraDemoActivity.kt:326)
        at com.google.android.gms.maps.zzu.zzb(com.google.android.gms:play-services-maps@@18.0.0:1)
        at com.google.android.gms.maps.internal.zzu.zza(com.google.android.gms:play-services-maps@@18.0.0:2)
        at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.0.0:3)
        at android.os.Binder.transact(Binder.java:1064)
```

**Comment by arriolac** [comment]
Closed by #796
